const names = [
  "Sandra Vicente",
  "Amparo Arias",
  "Floyd Pearson",
  "Emma Lemoine",
  "Lilja Karimi",
  "Ali Akşit",
  "Ömür Kunt",
  "Victoria Poulsen",
  "Oliver Anderson",
  "Sofia Garcia",
  "James Wilson",
  "Mia Chen",
];
const namesAr = [
  "ساندرا فيسينتي",
  "أمبارو أرياس",
  "فلويد بيرسون",
  "إيما لوموان",
  "ليليا كاريمي",
  "علي أكشيت",
  "عمر كونت",
  "فيكتوريا بولسن",
  "أوليفر أندرسون",
  "صوفيا غارسيا",
  "جيمس ويلسون",
  "ميا تشين",
];
const base = Date.UTC(2026, 9, 3, 18, 47);
const conversation = [
  ["apple", "Hey Sandra!"],
  ["orange", "Hey! How are you?"],
  ["orange", "Did you get a chance to look at the proposal?"],
  ["apple", "Yes, just finished reading it."],
  ["apple", "I like the direction. Let’s go with it."],
  ["orange", "Great. We should catch up before Friday."],
  ["apple", "Coffee tomorrow?"],
  ["orange", "That works. Around 10?"],
  ["apple", "Perfect, see you then ☕"],
  ["orange", "See you tomorrow!"],
];
const snippets = [
  "See you tomorrow!",
  "Please let me know. Thanks!",
  "Are we still on for Friday?",
  "The photos turned out so well",
  "I’ll send you the address",
  "أشوفك بكرة إن شاء الله",
  "Sounds good to me 👍",
  "I’ll be there at 8",
  "Thanks for the recommendation",
  "Can you send me that link?",
  "Happy birthday! 🎉",
  "Let’s catch up soon",
];
export const demoConversations = names.map((name, index) => ({
  id: `contact-${index + 1}`,
  name,
  nameAr: namesAr[index],
  unread: [0, 3, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0][index],
  photo: `/avatars/contact-${index + 1}.jpg`,
  messages: (index === 0 ? conversation : [["orange", snippets[index]]]).map(
    ([author, message], i) => ({
      id: `demo-${index}-${i}`,
      author,
      message,
      messageKey: `demo_${index === 0 ? `chat_${i}` : `snippet_${index}`}`,
      timestamp: base + (index === 0 ? i * 60000 : -index * 25 * 60000),
    }),
  ),
}));
